[package]
name = "wasmcloud-control-interface"
version = "0.28.1"
authors = ["wasmCloud Team"]
edition = "2021"
homepage = "https://wasmcloud.com"
repository = "https://github.com/wasmCloud/control-interface-client"
description = "A client library for communicating with hosts on a wasmCloud lattice"
license = "Apache-2.0"
documentation = "https://docs.rs/wasmcloud-control-interface"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasmcloud", "control", "ctl"]
categories = ["wasm", "api-bindings"]

[dependencies]
async-nats = "0.31"
data-encoding = "2.3.3"
ring = "0.16.20"
cloudevents-sdk = "0.7.0"
futures = "0.3"
rmp-serde = "1.0.0"
tokio = { version="1.9", features=["time"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
tracing = "0.1.37"
tracing-futures = "0.2"
bytes = "1.4.0"
opentelemetry = "0.19.0"
tracing-opentelemetry = "0.19.0"
lazy_static = "1.4.0"
