[package]
name = "wasmcloud-control-interface"
version = "0.17.0"
authors = ["wasmCloud Team"]
edition = "2021"
homepage = "https://wasmcloud.dev"
repository = "https://github.com/wasmCloud/control-interface-client"
description = "A client library for communicating with hosts on a wasmCloud lattice"
license = "Apache-2.0"
documentation = "https://docs.rs/wasmcloud-control-interface"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasmcloud", "control", "ctl"]
categories = ["wasm", "api-bindings"]

[dependencies]
async-trait = "0.1"
async-nats = "0.18.0"
data-encoding = "2.3.1"
cloudevents-sdk = "0.5.0"
futures = "0.3"
ring = "0.16.20"
rmp-serde = "1.0.0"
tokio = {version="1.9", features=["time"]}
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
tracing = "0.1.35"
tracing-futures = "0.2"
uuid = {version = "1.0.0", features  = ["serde", "v4"]}
wascap = "0.8.0"
wasmbus-rpc = {version = "0.9.0", features = ["otel"]}
