[package]
name = "wasmcloud-control-interface"
version = "0.10.2"
authors = ["wasmCloud Team"]
edition = "2021"
homepage = "https://wasmcloud.dev"
repository = "https://github.com/wasmCloud/control-interface-client"
description = "This library, when combined with a NATS client, allows interaction with the lattice control interface"
license = "Apache-2.0"
documentation = "https://docs.rs/wasmcloud-control-interface"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasmcloud", "control", "ctl"]
categories = ["wasm", "api-bindings"]

[dependencies]
async-trait = "0.1"
data-encoding = "2.3.1"
chrono = "0.4.19"
cloudevents-sdk = "0.4.0"
futures = "0.3"
log = "0.4.14"
crossbeam-channel = "0.5.1"
ring = "0.16.20"
rmp-serde = "1.0.0"
tokio = {version="1.9", features=["time"]}
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
uuid = {version = "0.8", features  = ["serde", "v4"]}
wascap = "0.6.0"
wasmbus-rpc-06 = { version = "0.6", package="wasmbus-rpc" }
wasmbus-rpc = "0.7.0-alpha.1"
wasmcloud-interface-lattice-control = "0.5.0"
