name: CONTROL_INTERFACE

on:
  push:
    branches: [ main ]
    tags:
    - 'wasmcloud-control-interface-v*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  working-directory: ./

jobs:
  rust_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wasmcloud/common-actions/run-nats@main
      with:
        options: '-js'

    - name: Update rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: install_protoc
      run: sudo apt-get install -y protobuf-compiler
    - id: rust-check-action
      uses: wasmcloud/common-actions/rust-check@main
      with:
        working-directory: ${{ env.working-directory }}

  github_release:
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: rust_check
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: true

  crates_release:
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: github_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: crates-release-action
        uses: wasmcloud/common-actions/crates-release@main
        with:
          working-directory: ${{ env.working-directory }}
          crates-token: ${{ secrets.CRATES_PUBLISH_TOKEN }}
